# CRU Thesis Configuration File
# Central settings for data paths, figure outputs, and reproducibility

project:
  name: "Causal Resonance Unification (CRU) Thesis"
  version: "1.0.0"
  description: >
    Repository structure and build configuration for the CRU thesis.
    All paths and outputs defined here are used by scripts and CI.

paths:
  data: "data/"
  figures: "figures/"
  tables: "tables/"
  scripts: "scripts/"
  tests: "tests/"
  thesis: "CRU_thesis.tex"

build:
  latex_engine: "pdflatex"
  bib_tool: "bibtex"
  output_pdf: "CRU_thesis.pdf"

ci:
  workflows:
    - ".github/workflows/latex.yml"
    - ".github/workflows/python.yml"

checks:
  figures_required:
    - "figures/cmb_power_spectrum.pdf"
    - "figures/dm_limits.pdf"
    - "figures/gw_prediction.pdf"
    - "figures/unhecr_spectrum.pdf"
    - "figures/cru_resonance_spectrum_basic.png"
    - "figures/cru_resonance_spectrum_full.png"
    - "figures/cru_cosmo_constraints.png"
    - "figures/cru_roadmap_flowchart.png"
    - "figures/cru_falsification_tree.png"
    - "figures/cru_noise_vs_signal.png"
    - "figures/cru_master_map.png"
  tables_required:
    - "tables/resonant_anchors.tex"
    - "tables/verification_table.tex"
    - "tables/cosmo_constraints.tex"
    - "tables/experimental_protocols.tex"
    - "tables/unhecr_table.tex"
